name = "modcast"
license = "MIT"
licenselink = "https://github.com/alroniks/hugo-theme-modcast/blob/master/LICENSE"
description = "A podcast-oriented theme for Hugo based on Bulma CSS framework"
tags = ["podcast", "responsive", "minimal", "bulma"]
features = ["Podcast RSS"]

[author]
  name = "Ivan Klimchuk"
  homepage = "https://klimchuk.com"
